CREATE TABLE `user` (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户ID',
    `openid` VARCHAR(64) DEFAULT NULL COMMENT '微信 openid',
    `unionid` VARCHAR(64) DEFAULT NULL COMMENT '微信 unionid（可跨平台）',
    `nickname` VARCHAR(100) DEFAULT NULL COMMENT '微信昵称',
    `avatar` VARCHAR(255) DEFAULT NULL COMMENT '微信头像 URL',
    `gender` TINYINT UNSIGNED DEFAULT 0 COMMENT '性别：0=未知，1=男，2=女',
    `phone` VARCHAR(20) DEFAULT NULL COMMENT '手机号（用户主动绑定时）',
    `username` VARCHAR(50) DEFAULT NULL COMMENT '用户名（账号密码登录时使用）',
    `password` VARCHAR(255) DEFAULT NULL COMMENT '密码（账号密码登录时使用）',
    `certification_type` ENUM('none','personal','enterprise') DEFAULT 'none' COMMENT '认证类型：none=未认证，personal=个人认证，enterprise=企业认证',
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_openid` (`openid`),
    UNIQUE KEY `uk_phone` (`phone`),
    UNIQUE KEY `uk_username` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';


CREATE TABLE `personal_certification` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '认证ID',
  `user_id` INT UNSIGNED NOT NULL COMMENT '用户ID，关联user表',
  `name` VARCHAR(50) NOT NULL COMMENT '真实姓名',
  `gender` ENUM('男','女') NOT NULL COMMENT '性别',
  `region_province` VARCHAR(50) COMMENT '省份',
  `region_city` VARCHAR(50) COMMENT '城市', 
  `region_district` VARCHAR(50) COMMENT '区县',
  `identity_type` VARCHAR(50) COMMENT '身份类型（学生/教师/医生等）',
  `job_title` VARCHAR(100) COMMENT '职称职务',
  `expertise` VARCHAR(200) COMMENT '擅长领域',
  `company` VARCHAR(200) COMMENT '所在企业',
  `is_vip` TINYINT(1) DEFAULT 0 COMMENT '是否VIP嘉宾',
  `vip_code` VARCHAR(50) COMMENT 'VIP嘉宾码',
  `photo_image` VARCHAR(255) COMMENT '形象照片URL',
  `id_front_image` VARCHAR(255) COMMENT '身份证正面照片URL',
  `id_back_image` VARCHAR(255) COMMENT '身份证背面照片URL',
  `doctor_cert_image` VARCHAR(255) COMMENT '医师资格证照片URL',
  `qualification_cert_image` VARCHAR(255) COMMENT '资格证书照片URL',
  `other_cert1_image` VARCHAR(255) COMMENT '其他证书1照片URL',
  `other_cert2_image` VARCHAR(255) COMMENT '其他证书2照片URL',
  `status` ENUM('pending','approved','rejected') DEFAULT 'pending' COMMENT '认证状态',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_id` (`user_id`),
  FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='个人认证表';


CREATE TABLE `enterprise_certification` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '认证ID',
  `user_id` INT UNSIGNED NOT NULL COMMENT '用户ID，关联user表',
  `company_name` VARCHAR(200) NOT NULL COMMENT '企业名称',
  `company_logo` VARCHAR(255) COMMENT '企业形象照片URL',
  `region_province` VARCHAR(50) COMMENT '省份',
  `region_city` VARCHAR(50) COMMENT '城市',
  `region_district` VARCHAR(50) COMMENT '区县',
  `enterprise_type` VARCHAR(50) COMMENT '企业类型',
  `enterprise_field` VARCHAR(50) COMMENT '所属领域',
  `business_license` VARCHAR(255) COMMENT '营业执照照片URL',
  `medical_license` VARCHAR(255) COMMENT '医疗许可证照片URL',
  `device_license` VARCHAR(255) COMMENT '医疗器械经营许可证照片URL',
  `legal_person_name` VARCHAR(50) NOT NULL COMMENT '法人姓名',
  `legal_person_id` VARCHAR(20) NOT NULL COMMENT '法人身份证号',
  `legal_person_id_front` VARCHAR(255) COMMENT '法人身份证正面照片URL',
  `legal_person_id_back` VARCHAR(255) COMMENT '法人身份证背面照片URL',
  `bank_name` VARCHAR(100) COMMENT '开户银行',
  `bank_account` VARCHAR(50) COMMENT '银行账户',
  `agree_terms` TINYINT(1) DEFAULT 0 COMMENT '是否同意协议',
  `status` ENUM('pending','approved','rejected') DEFAULT 'pending' COMMENT '认证状态',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_id` (`user_id`),
  FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='企业认证表';